@startuml
title Пример развертывания веб-приложения

' Меняем направление на горизонтальное
' left to right direction

' Элементы
node "ПК пользователя" {
    component "Браузер"
}

cloud "Интернет"    /' задаем фигуру облако '/

node "Сервер" {
    component "Веб-сервер"
    database db1 [  /' задаем фигуру БД '/
<b>"database"</b>
----
   MySQL
]
}

' Связи
"Браузер" --> "Интернет" : " Запросы"
"Интернет" --> "Веб-сервер" : " tcp 80/443"
"Веб-сервер" -left-> db1 : "Чтение- \nзапись"  /' направление связи слева направо '/


note top of db1 : Данные \nпользователей  /' комментарий сверху от БД '/

@enduml