@startuml
title Пример развертывания веб-приложения

' Меняем направление на горизонтальное
left to right direction
' Элементы
node "ПК пользователя" {
    component "Браузер"
}

cloud "Интернет"

node "Сервер" {
    component "Веб-сервер"
    database db1 [
<b><database></b>
----
MySQL
]
}

' Связи
"Браузер" --> "Интернет" : "Запросы"
"Интернет" --> "Веб-сервер" : "tcp 80/443"
"Веб-сервер" --> db1 : "Чтение- \nзапись"


note bottom of db1 : Данные пользователей

@enduml